entrada=input('Digite algo : ')
print('O tipo primitivo desse valor é {}'.format(type(entrada)))
print('Só tem espaços? {}'.format((entrada).isspace()))
print('É um número? {}'.format((entrada).isnumeric()))
print('É alfabético? {}'.format((entrada).isalpha()))
print('É alfanumérico? {}'.format((entrada).isalnum()))
print('Esta em maiúscula? {}'.format((entrada).isupper()))
print('Esta em minuscula? {}'.format((entrada).islower()))
print('Esta capitalizada? {}'.format((entrada).istitle()))
